Library Project completion
Zibilyonik/library-project pull request #1
Opened 2021-05-28 10:11 UTC by Zibilyonik

2021-05-28 10:38 UTC, mimipeshy commented
## STATUS : INVALID SUBMISSION 🔴 

Hello there @Zibilyonik and @TSHEPO-CLOUD 👋🏾 great job so far. However, I cannot review your work because your PR is not professional. A Pull Request should have a meaningful title and a brief description as described [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png)

That's all 😄, kindly submit another review when done
If you need any clarification, kindly post your comment here and tag me @mimipeshy and will be glad to help

Regards,
Peris Ndanu

2021-05-28 11:02 UTC, whiz25 requested changes
## Changes Required 🙏🏿 🙏🏿 🙏🏿 
Nice work on this project. 
### Highlights 🌵 🌵 🌵 
- A user can create a book, mark it as read and delete

### Change(s) to be made 🙅🏿 🙅🏿 🙅🏿 
- Remove comments from your code. They make the codebase look ugly
- Update the readme with instructions for getting started with your project
- Separate JS logic from dom-manipulation logic. Check comments.

### Martin Afani
#### Slack: whiz25

2021-05-28 11:02 UTC, whiz25 commented on README.md
> +- SASS
- Add a section for `Getting Started`. Add explicit commands for cloning, installing packages, and running the app locally.

2021-05-28 11:02 UTC, whiz25 commented on library.js
> +function Book(title, author, pages, read) {
- Organize your code into modules. Create a folder `src/modules` and move this file there.

2021-05-28 11:02 UTC, whiz25 commented on library.js
> +  libarray.push(first);
- Separate JS logic from DOM manipulation logic. Create a file `src/dom.js` and move any dom-manipulation logic there.

2021-05-28 11:02 UTC, whiz25 commented on library.js
> +// Button listeners to trigger certain events
- Delete all comments from the codebase

2021-05-28 11:02 UTC, whiz25 commented on library.js
> +function GetBook() {
- Modularise your code. First, define a book model in `src/modules/book.js` before doing operations such as this on the book object.
```javascript
function Book(name, author, pages, read) {
    this.name = name;
    this.author = author;
    this.pages = pages;
    this.read = read;
}
```
- Now you can create a dummy list for books
```javascript
let books = [
Book('','','','')
]
```
- Create a function to loop through the list of books and return the list to your dom-manipulation to be rendered in the UI.

2021-05-30 18:34 UTC, Torres-ssf approved these changes
### PR Approved :+1: 
Hello team :hand: 
Good job on this project 
Good luck with the next one

Happy coding :computer: 
**Sérgio Torres**

2021-05-30 18:37 UTC, merged